name: Build (Linux)

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run sip-install
        run: |
          perl build.pl

      - name: Create artifact tar.gz
        run: |
          tar -czf sip-exp-linux.tar.gz *

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: sip-exp-linux
          path: sip-exp-linux.tar.gz
