name: Build (Windows)

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
        shell: powershell

      - name: Run sip-install
        run: |
          perl build.pl
        shell: powershell

      - name: Create artifact zip
        run: |
          Compress-Archive -Path * -DestinationPath sip-exp-win.zip
        shell: powershell

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: sip-exp-windows
          path: sip-exp-win.zip
